export const initialState = {
  categories: [
    { value: 1, title: "Sport" },
    { value: 2, title: "News" },
    { value: 3, title: "Movies" },
  ],
  posts: [
    {
      id: "1",
      title: "Article title",
      shortDescription: "Short description of the article...",
      content: "Main content of the article",
      publishedDate: new Date("02-02-2022"),
      category: 2,
      author: "John Doe",
    },
    {
      id: "2",
      title: "Article title",
      shortDescription: "Short description of the article...",
      content: "Main content of the article",
      publishedDate: new Date("02-02-2022"),
      category: 1,
      author: "John Doe",
    },
    {
      id: "3",
      title: "Article title",
      shortDescription: "Short description of the article...",
      content: "Main content of the article",
      publishedDate: new Date("02-02-2022"),
      category: 3,
      author: "John Doe",
    },
    {
      id: "4",
      title: "Article title",
      shortDescription: "Short description of the article...",
      content: "Main content of the article",
      publishedDate: new Date("02-02-2022"),
      category: 2,
      author: "John Doe",
    },
  ],
};
